apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: zeroworkshop

resources:
  - namespace.yml

secretGenerator:
- name: zeroworkshop
  env: secrets.env

# Don't add a suffix to the secret name
generatorOptions:
  disableNameSuffixHash: true
