apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesStrategicMerge:
- deployment.yml

resources:
- ../../base
- ingress.yml

configMapGenerator:
- name: zeroworkshop-config
  behavior: merge
  literals:
    - DATABASE_HOST=
    - DATABASE_NAME=zeroworkshop-stage
    - ENVIRONMENT=staging
